---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: ru-staging-
commonLabels:
  env: env-staging
patchesStrategicMerge:
  - greet-overlay.yaml
components:
  - ../../components