---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: ru-prod-
commonLabels:
  env: ru-prod
patchesStrategicMerge:
  - greet-overlay.yaml
components:
  - ../../components