---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test
spec:
    template:
        spec:
          containers:
            - name: main
              resources:
                limits:
                  cpu: 300m
                  memory: 300Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
